
const tech = [
    "The rise of quantum computing",
    "The impact of 5G technology",
    "The future of virtual reality",
    "Artificial intelligence in healthcare",
    "Cybersecurity threats and solutions",
    "The role of blockchain in modern business",
    "Advancements in cloud computing",
    "The development of autonomous vehicles",
    "Ethical considerations in AI development",
    "The evolution of mobile technology",
    "How IoT is transforming industries",
    "The impact of tech on job automation",
    "Wearable technology and health",
    "The future of augmented reality",
    "Tech startups to watch in 2024",
    "The role of big data in decision making",
    "Smart home technology trends",
    "The implications of tech on privacy",
    "Emerging programming languages",
    "The significance of open-source software",
    "Trends in tech entrepreneurship",
    "The effects of tech on mental health",
    "Advancements in semiconductor technology",
    "The role of tech in disaster response",
    "The future of human-computer interaction",
    "How tech is changing remote work",
    "Tech innovations in education",
    "The rise of digital currencies",
    "Robotics and automation in manufacturing",
    "The impact of tech on environmental sustainability",
    "Developments in machine learning algorithms",
    "The role of tech in smart cities",
    "Tech solutions for global challenges",
    "The future of bioengineering",
    "The evolution of user interfaces",
    "Challenges in tech regulation",
    "The impact of tech on personal relationships",
    "The role of tech in creative industries",
    "The ethics of data collection",
    "The future of computer graphics",
    "Emerging trends in e-commerce",
    "The impact of 3D printing on manufacturing",
    "Trends in digital marketing",
    "The role of AI in financial services",
    "The future of tech in entertainment",
    "Advances in natural language processing",
    "Tech and the gig economy",
    "The role of tech in public health",
    "Developments in renewable energy technology",
    "The influence of tech on global politics",
    "Challenges in tech supply chains",
    "The future of online education",
    "The impact of tech on traditional industries",
    "Tech innovations in transportation",
    "The rise of edge computing",
    "The significance of tech in space exploration",
    "Tech and the future of work",
    "The role of tech in improving accessibility",
    "Advancements in network technology",
    "The influence of tech on consumer behavior",
    "The future of tech in sports",
    "Ethical issues in tech development",
    "Tech's role in combating climate change",
    "The impact of tech on creative processes",
    "The evolution of tech hardware",
    "The role of tech in social justice",
    "Trends in tech-based startups",
    "The future of drone technology",
    "Tech's influence on global communication",
    "The impact of tech on education equity",
    "Advancements in digital health",
    "The role of tech in disaster recovery",
    "The future of tech in agriculture",
    "Tech and its impact on traditional media",
    "The influence of tech on personal finance",
    "Challenges in tech ethics",
    "The role of tech in cultural preservation",
    "Emerging trends in tech gadgets",
    "The future of smart appliances",
    "Tech's role in crisis management",
    "Advancements in computational biology",
    "The influence of tech on urban development",
    "The impact of tech on public safety",
    "The future of tech in hospitality",
    "Challenges in global tech policy",
    "The role of tech in enhancing creativity",
    "The impact of tech on traditional retail",
    "The future of tech in the arts",
    "Tech and its role in reducing inequality",
    "The significance of tech in scientific research",
    "Advancements in tech infrastructure",
    "The role of tech in enhancing education",
    "The future of tech in financial services",
    "Tech innovations in environmental monitoring",
    "The impact of tech on healthcare access",
    "The role of tech in fostering innovation",
    "The future of tech in personal productivity",
    "Tech and the evolution of online communities",
    "The impact of tech on transportation safety",
    "Challenges in tech adoption",
    "The role of tech in improving governance",
    "Advancements in tech-driven research methodologies",
    "The future of tech in gaming",
    "Tech's influence on global economic trends",
    "The role of tech in enhancing communication",
    "The impact of tech on social behavior",
    "Challenges in tech scalability"
];

const movie = [
    "The evolution of film genres",
    "Iconic directors of the 21st century",
    "The impact of digital technology on filmmaking",
    "Trends in independent cinema",
    "The role of special effects in modern movies",
    "The influence of streaming platforms on cinema",
    "The rise of international films in Hollywood",
    "Cinematic adaptations of popular books",
    "The future of virtual reality in movies",
    "Film score composers who changed the industry",
    "The significance of film festivals",
    "The impact of social media on movie marketing",
    "Classic films that defined their genre",
    "The role of cinematography in storytelling",
    "The resurgence of cult classics",
    "The influence of historical events on cinema",
    "Women directors who shaped the industry",
    "The evolution of animated films",
    "The role of costumes and set design in film",
    "The impact of box office trends on movie production",
    "The significance of film editing in storytelling",
    "Documentaries that changed public opinion",
    "The role of film criticism in shaping cinema",
    "The future of AI in film production",
    "How film portrays social issues",
    "The rise of superhero movies",
    "The influence of film on popular culture",
    "Remakes and reboots in contemporary cinema",
    "The role of film in cultural diplomacy",
    "How film genres have evolved over decades",
    "The impact of film on fashion trends",
    "The significance of film in historical documentation",
    "The rise of female-led films",
    "The role of film in political movements",
    "Iconic movie scenes that changed cinema",
    "The future of film distribution",
    "The role of the film producer",
    "Film's representation of different cultures",
    "The impact of film awards on the industry",
    "The influence of film on music trends",
    "How film explores human psychology",
    "The role of improvisation in film",
    "The future of film technology",
    "The impact of censorship on filmmaking",
    "The evolution of film criticism",
    "The role of film in education",
    "How film handles controversial subjects",
    "The influence of film on global politics",
    "The role of film in shaping societal norms",
    "The significance of film soundtracks",
    "How film addresses environmental issues",
    "The impact of international box office on Hollywood",
    "The role of film in exploring identity",
    "The future of film in virtual reality",
    "The significance of film preservation",
    "How film portrays mental health",
    "The impact of film on youth culture",
    "The evolution of film studios",
    "The role of film in societal change",
    "How film adaptations differ from their sources",
    "The impact of film on literature",
    "The role of film in bridging cultural gaps",
    "The significance of film's visual storytelling",
    "The rise of streaming services and their impact",
    "The role of film in reflecting social change",
    "The influence of cinema on art",
    "The future of interactive storytelling in film",
    "The significance of film in shaping perceptions",
    "How film handles historical events",
    "The role of film in popularizing technology",
    "The impact of global cinema on Hollywood",
    "The evolution of film formats",
    "The influence of film on societal values",
    "The future of film in a digital world",
    "The role of film in fostering community",
    "How film portrays diverse perspectives",
    "The significance of film in entertainment history",
    "The impact of film on global tourism",
    "The role of film in shaping public opinion",
    "How film addresses moral dilemmas",
    "The evolution of movie marketing strategies"
];

const history = [
    "The fall of the Roman Empire",
    "The impact of the Industrial Revolution",
    "Key events of World War I",
    "The significance of the Renaissance",
    "The rise and fall of the Ottoman Empire",
    "The history of the American Civil War",
    "The French Revolution and its impacts",
    "The influence of the Enlightenment on modern society",
    "The Cold War era",
    "The history of ancient Egypt",
    "The role of the Silk Road in global trade",
    "The history of the Ming Dynasty",
    "The impact of colonialism in Africa",
    "The history of the Byzantine Empire",
    "The origins and impact of the Protestant Reformation",
    "The significance of the Enlightenment",
    "The history of the Vikings",
    "The impact of the Great Depression",
    "Key events of World War II",
    "The history of the Inca Empire",
    "The origins of the American Revolution",
    "The role of the Mongol Empire in Eurasian history",
    "The history of the Samurai",
    "The impact of the scientific revolution",
    "The history of the Aztec Empire",
    "The rise of nationalism in the 19th century",
    "The history of the French Empire",
    "The significance of the Treaty of Versailles",
    "The impact of the Russian Revolution",
    "The history of the Greek city-states",
    "The role of women in ancient societies",
    "The history of medieval Europe",
    "The influence of the Roman Empire on modern law",
    "The significance of the Berlin Wall",
    "The impact of the Renaissance on art",
    "The history of the Crusades",
    "The role of trade routes in medieval economics",
    "The history of feudal Japan",
    "The impact of the Age of Exploration",
    "The history of the British Empire",
    "The influence of the Reformation on modern Christianity",
    "The history of the Ottoman sultans",
    "The significance of the Magna Carta",
    "The impact of the Spanish Civil War",
    "The history of the Italian Renaissance",
    "The role of propaganda in World War I",
    "The significance of the Cold War arms race",
    "The history of the Silk Road",
    "The impact of the French and Indian War",
    "The history of the U.S. Civil Rights Movement",
    "The rise of the Soviet Union",
    "The history of the Native American tribes",
    "The significance of the Treaty of Paris",
    "The impact of the Korean War",
    "The history of medieval castles",
    "The role of exploration in shaping the modern world",
    "The history of early American settlers",
    "The influence of Ancient Greece on Western philosophy",
    "The significance of the Cuban Missile Crisis",
    "The impact of the World Wars on technology",
    "The history of major world religions",
    "The role of the United Nations in post-war history",
    "The history of the development of democracy",
    "The impact of the French Revolution on Europe",
    "The significance of the Reformation in European politics",
    "The history of the transatlantic slave trade",
    "The rise and fall of ancient civilizations",
    "The history of the American West",
    "The role of espionage during the Cold War",
    "The significance of the fall of Constantinople",
    "The impact of the Great Wall of China",
    "The history of the Middle Ages",
    "The significance of the Industrial Age inventions",
    "The role of religion in shaping history",
    "The history of the space race",
    "The impact of the Renaissance on science",
    "The significance of the Age of Enlightenment",
    "The history of political revolutions",
    "The role of cultural exchange in world history",
    "The significance of the Enlightenment thinkers",
    "The impact of World War II on the modern world"
];
const memes = [
   
        "Distracted Boyfriend",
        "Pepe the Frog",
        "Mocking SpongeBob",
        "Woman Yelling at a Cat",
        "Success Kid",
        "Drake Hotline Bling",
        "Change My Mind",
        "Kermit Drinking Tea",
        "Expanding Brain",
        "Roll Safe",
        "Is This a Pigeon?",
        "Two Buttons",
        "Surprised Pikachu",
        "Arthur Fist",
        "Swole Doge vs. Cheems",
        "How Do You Do, Fellow Kids?",
        "Doge",
        "Confused Math Lady",
        "Gonna Tell My Kids",
        "Evil Kermit",
        "Big Brain Time",
        "Galaxy Brain",
        "Left Exit 12 Off Ramp",
        "Hide the Pain Harold",
        "Ancient Aliens",
        "Stonks",
        "The Scroll of Truth",
        "Pikachu Face",
        "Bernie Sanders Mittens",
        "One Does Not Simply",
        "The Most Interesting Man in the World",
        "Distracted Boyfriend",
        "Bad Luck Brian",
        "Ironic SpongeBob",
        "Me Explaining",
        "Grumpy Cat",
        "PepeLaugh",
        "Yodelling Kid",
        "SpongeBob Ight Imma Head Out",
        "Moth and Lamp",
        "Doggo",
        "No One: Absolutely No One:",
        "Yoda Best",
        "Simpsons Did It",
        "American Chopper Argument",
        "Mocking SpongeBob",
        "Drake vs. Kanye",
        "Me_irl",
        "The Office Dinner Party",
        "Confused Nick Young",
        "Can I Copy Your Homework?",
        "When You See It",
        "Distracted Boyfriend",
        "Deep Fried Memes",
        "Spicy Memes",
        "Triggered",
        "Doge",
        "PepeHands",
        "Shrek Is Love",
        "The Rock Driving",
        "SpongeBob Ight Imma Head Out",
        "Harambe",
        "Who Asked?",
        "Meme Man",
        "Nyan Cat",
        "I Like Your Cut G",
        "Karen",
        "Doge",
        "Liar Liar Pants on Fire",
        "PepeLaugh",
        "You Know I Had to Do It to Em",
        "Hide the Pain Harold",
        "Epic Sax Guy",
        "Swole Doge",
        "You Get What You Fucking Deserve",
        "Popeyes vs. Chick-fil-A",
        "The Most Interesting Man in the World",
        "Crying Jordan",
        "Mocking SpongeBob",
        "Weird Flex But OK",
        "Bean Dad",
        "Wojak",
        "Meme Review",
        "Trumpet Guy",
        "Cat vs. Dog",
        "Wacky Waving Inflatable Arm Flailing Tube Man",
        "Where’s the Lambo?",
        "Shooketh",
        "Meme Generator",
        "Crab Rave",
        "Doge",
        "Surprised Pikachu",
        "Ugandan Knuckles",
        "Pepe the Frog",
        "Literally Who Asked?",
        "Doge",
        "I'm a Believer",
        "He Protec But He Also Attac",
        "Feeling Cute",
        "Noob",
        "Llama Arts",
        "Weird Al Yankovic",
        "Baby Yoda",
        "Yes Chad",
        "That's What She Said",
        "Is This Loss?",
        "Doge Meme Evolution",
        "Distracted Boyfriend Redux",
        "Swole Doge vs. Cheems Redux",
        "Homer Simpson Walking Into Room",
        "Evil Kermit Redux",
        "Wholesome Memes",
        "The Most Interesting Man in the World Redux",
        "Success Kid Redux",
        "Grumpy Cat Redux",
        "Mocking SpongeBob Redux",
        "Yoda Best Redux",
        "Surprised Pikachu Redux",
        "Doge Redux",
        "Expanding Brain Redux",
        "Roll Safe Redux",
        "Arthur Fist Redux",
        "PepeLaugh Redux",
        "Woman Yelling at a Cat Redux",
        "Kermit Drinking Tea Redux",
        "Confused Math Lady Redux",
        "The Scroll of Truth Redux",
        "PepeHands Redux",
        "Shrek Is Love Redux",
        "I Like Your Cut G Redux",
        "Bean Dad Redux",
        "Wojak Redux",
        "Crab Rave Redux",
        "Deep Fried Memes Redux",
        "Triggered Redux",
        "Drake Hotline Bling Redux",
        "Change My Mind Redux",
        "The Rock Driving Redux",
        "American Chopper Argument Redux",
        "Nyan Cat Redux",
        "Meme Generator Redux",
        "Pikachu Face Redux",
        "Bernie Sanders Mittens Redux",
        "The Office Dinner Party Redux",
        "Simpsons Did It Redux",
        "When You See It Redux",
        "No One: Absolutely No One: Redux",
        "Feeling Cute Redux",
        "Epic Sax Guy Redux",
        "Who Asked? Redux",
        "Yodelling Kid Redux",
        "Doge Meme Phenomenon",
        "Meme Man Redux",
        "Surprised Pikachu Phenomenon",
        "Ironic SpongeBob Redux",
        "How Do You Do, Fellow Kids? Redux",
        "Moth and Lamp Redux",
        "SpongeBob Ight Imma Head Out Redux",
        "Doge Meme Nostalgia",
        "Confused Nick Young Redux",
        "Literally Who Asked? Redux",
        "Doge Meme Variety Pack",
        "Distracted Boyfriend Phenomenon",
        "Drake vs. Kanye Redux",
        "The Most Interesting Man in the World Redux 2",
        "Doge Meme Culture",
        "Wacky Waving Inflatable Arm Flailing Tube Man Redux",
        "The Rock Driving Meme Redux",
        "Shooketh Redux",
        "Harambe Redux",
        "Cat vs. Dog Redux",
        "Meme Review Redux",
        "Epic Sax Guy Redux 2",
        "Crying Jordan Redux",
        "Bean Dad Redux 2",
        "Meme Generator Phenomenon",
        "Pepe the Frog Redux",
        "I'm a Believer Redux",
        "Surprised Pikachu Meme Trends",
        "Yoda Best Meme Trends",
        "Distracted Boyfriend Trends",
        "Deep Fried Memes Redux",
        "Baby Yoda Redux",
        "PepeLaugh Meme Culture",
        "Drake Hotline Bling Meme Evolution",
        "Mocking SpongeBob Meme Trends",
        "Swole Doge vs. Cheems Meme Trends",
        "The Rock Driving Meme Trends",
        "Wojak Meme Culture",
        "Meme Man Meme Culture",
        "Meme Review Meme Evolution",
        "Shrek Is Love Meme Trends",
        "Who Asked? Meme Evolution",
        "Feeling Cute Meme Trends",
        "Doge Meme Trends",
        "Confused Math Lady Meme Evolution",
        "Yodelling Kid Meme Trends",
        "Crab Rave Meme Trends",
        "Surprised Pikachu Meme Evolution",
        "The Scroll of Truth Meme Trends",
        "American Chopper Argument Meme Trends",
        "Epic Sax Guy Meme Culture",
        "Bean Dad Meme Culture",
        "SpongeBob Ight Imma Head Out Meme Evolution",
        "I Like Your Cut G Meme Trends",
        "Doge Meme Redux",
        "Meme Generator Meme Evolution",
        "Hide the Pain Harold Redux",
        "Stonks Redux",
        "Galaxy Brain Redux",
        "Roll Safe Meme Evolution",
        "Expanding Brain Meme Evolution",
        "How Do You Do, Fellow Kids? Meme Trends",
        "Doge Meme Renaissance",
        "Confused Math Lady Meme Trends",
        "Evil Kermit Meme Culture",
        "The Most Interesting Man in the World Meme Trends",
        "The Scroll of Truth Meme Culture",
        "Distracted Boyfriend Meme Culture",
        "PepeHands Meme Evolution",
        "Shrek Is Love Meme Evolution",
        "Surprised Pikachu Meme Culture",
        "Feeling Cute Meme Evolution",
        "Meme Man Meme Trends",
        "Surprised Pikachu Redux",
        "Baby Yoda Meme Trends",
        "Pepe the Frog Meme Trends",
        "Confused Math Lady Meme Trends",
        "The Rock Driving Meme Evolution",
        "The Scroll of Truth Meme Trends",
        "Swole Doge Meme Evolution",
        "I Like Your Cut G Meme Evolution",
        "Harambe Meme Trends",
        "Meme Generator Meme Culture",
        "Yoda Best Meme Culture",
        "Bean Dad Meme Trends",
        "Wojak Meme Trends",
        "Nyan Cat Meme Trends",
        "Doge Meme Phenomenon",
        "Distracted Boyfriend Meme Evolution",
        "The Most Interesting Man in the World Meme Evolution",
        "Mocking SpongeBob Meme Culture",
        "SpongeBob Ight Imma Head Out Meme Trends",
        "Shooketh Meme Trends",
        "Crying Jordan Meme Trends",
        "Epic Sax Guy Meme Evolution",
        "PepeLaugh Meme Evolution",
        "Bean Dad Meme Culture",
        "Surprised Pikachu Meme Culture",
        "The Scroll of Truth Meme Evolution",
        "Meme Review Meme Culture",
        "The Rock Driving Meme Culture",
        "Swole Doge vs. Cheems Meme Evolution",
        "Doge Meme Renaissance",
        "Confused Nick Young Meme Trends",
        "Hide the Pain Harold Meme Evolution",
        "Wacky Waving Inflatable Arm Flailing Tube Man Meme Trends",
        "Doge Meme Trends",
        "The Scroll of Truth Meme Culture",
        "Stonks Meme Trends",
        "How Do You Do, Fellow Kids? Meme Evolution",
        "Feeling Cute Meme Culture",
        "American Chopper Argument Meme Evolution",
        "Distracted Boyfriend Meme Trends",
        "The Rock Driving Meme Culture",
        "Epic Sax Guy Meme Trends",
        "Confused Math Lady Meme Evolution",
        "Surprised Pikachu Meme Culture",
        "Pepe the Frog Meme Culture",
        "Meme Man Meme Trends",
        "Shrek Is Love Meme Culture",
        "Bean Dad Meme Evolution",
        "Baby Yoda Meme Culture",
        "I Like Your Cut G Meme Trends",
        "Doge Meme Culture",
        "Swole Doge Meme Trends",
        "Meme Generator Meme Trends",
        "The Scroll of Truth Meme Culture",
        "Distracted Boyfriend Meme Evolution",
        "Surprised Pikachu Meme Trends",
        "Confused Nick Young Meme Culture",
        "Nyan Cat Meme Trends",
        "Bean Dad Meme Culture",
        "The Most Interesting Man in the World Meme Culture",
        "Wacky Waving Inflatable Arm Flailing Tube Man Meme Evolution",
        "Mocking SpongeBob Meme Culture",
        "Doge Meme Trends",
        "Epic Sax Guy Meme Culture",
        "Surprised Pikachu Meme Evolution",
        "Feeling Cute Meme Trends",
        "The Rock Driving Meme Evolution",
        "SpongeBob Ight Imma Head Out Meme Culture",
        "Baby Yoda Meme Trends",
        "Shrek Is Love Meme Evolution",
        "Pepe the Frog Meme Trends",
        "Confused Math Lady Meme Trends",
        "Meme Man Meme Culture",
        "Distracted Boyfriend Meme Culture",
        "The Scroll of Truth Meme Evolution",
        "Doge Meme Trends",
        "The Rock Driving Meme Trends",
        "Surprised Pikachu Meme Culture",
        "Swole Doge Meme Culture",
        "Bean Dad Meme Evolution",
        "Mocking SpongeBob Meme Trends",
        "Baby Yoda Meme Culture",
        "Feeling Cute Meme Evolution",
        "Meme Review Meme Trends",
        "The Most Interesting Man in the World Meme Culture",
        "Doge Meme Evolution",
        "Surprised Pikachu Meme Trends",
        "Confused Nick Young Meme Trends",
        "Nyan Cat Meme Culture",
        "Swole Doge Meme Evolution",
        "Shrek Is Love Meme Trends",
        "Bean Dad Meme Trends",
        "Meme Generator Meme Culture",
        "The Scroll of Truth Meme Trends",
        "The Rock Driving Meme Culture",
        "Mocking SpongeBob Meme Evolution",
        "Baby Yoda Meme Trends",
        "Distracted Boyfriend Meme Culture",
        "Surprised Pikachu Meme Evolution",
        "Confused Math Lady Meme Trends",
        "Swole Doge Meme Trends",
        "Doge Meme Culture",
        "Feeling Cute Meme Trends",
        "Epic Sax Guy Meme Culture",
        "The Most Interesting Man in the World Meme Trends",
        "Bean Dad Meme Culture",
        "The Rock Driving Meme Evolution",
        "Meme Man Meme Trends",
        "Surprised Pikachu Meme Trends",
        "Distracted Boyfriend Meme Evolution",
        "Baby Yoda Meme Culture",
        "Shrek Is Love Meme Evolution",
        "Meme Review Meme Culture",
        "Confused Nick Young Meme Trends",
        "Nyan Cat Meme Trends",
        "Doge Meme Trends",
        "The Most Interesting Man in the World Meme Evolution",
        "Swole Doge Meme Culture",
        "Surprised Pikachu Meme Culture",
        "Bean Dad Meme Trends",
        "Epic Sax Guy Meme Trends",
        "Mocking SpongeBob Meme Culture",
        "Distracted Boyfriend Meme Trends",
        "Baby Yoda Meme Evolution",
        "Swole Doge Meme Trends",
        "Feeling Cute Meme Culture",
        "Doge Meme Evolution",
        "The Rock Driving Meme Trends",
        "Confused Math Lady Meme Evolution",
        "Surprised Pikachu Meme Trends",
        "The Most Interesting Man in the World Meme Trends",
        "Bean Dad Meme Evolution",
        "Mocking SpongeBob Meme Trends",
        "Shrek Is Love Meme Culture",
        "Distracted Boyfriend Meme Evolution",
        "Surprised Pikachu Meme Culture",
        "Feeling Cute Meme Trends",
        "Baby Yoda Meme Trends",
        "The Rock Driving Meme Evolution",
        "Epic Sax Guy Meme Culture",
        "Doge Meme Trends",
        "Bean Dad Meme Culture",
        "The Scroll of Truth Meme Evolution",
        "Swole Doge Meme Trends",
        "Confused Nick Young Meme Culture",
        "Distracted Boyfriend Meme Trends",
        "Surprised Pikachu Meme Culture",
        "Baby Yoda Meme Trends",
        "The Most Interesting Man in the World Meme Evolution",
        "Mocking SpongeBob Meme Trends",
        "Feeling Cute Meme Culture",
        "Doge Meme Culture",
        "Epic Sax Guy Meme Trends",
        "Bean Dad Meme Evolution",
        "Swole Doge Meme Culture",
        "The Rock Driving Meme Trends",
        "Surprised Pikachu Meme Evolution",
        "The Most Interesting Man in the World Meme Trends",
        "Baby Yoda Meme Culture",
        "Distracted Boyfriend Meme Evolution",
        "Confused Nick Young Meme Trends",
        "Mocking SpongeBob Meme Culture",
        "Doge Meme Trends",
        "Bean Dad Meme Trends",
        "Feeling Cute Meme Evolution",
        "Epic Sax Guy Meme Culture",
        "The Rock Driving Meme Evolution",
        "Swole Doge Meme Trends",
        "Surprised Pikachu Meme Culture",
        "Baby Yoda Meme Trends",
        "Distracted Boyfriend Meme Trends",
        "Confused Math Lady Meme Evolution",
        "The Most Interesting Man in the World Meme Culture",
        "Mocking SpongeBob Meme Trends",
        "Doge Meme Evolution",
        "Bean Dad Meme Culture",
        "Surprised Pikachu Meme Trends",
        "Feeling Cute Meme Evolution",
        "Epic Sax Guy Meme Trends",
        "Swole Doge Meme Culture",
        "The Rock Driving Meme Trends",
        "Baby Yoda Meme Evolution",
        "Confused Nick Young Meme Trends",
        "Distracted Boyfriend Meme Culture",
        "Mocking SpongeBob Meme Trends",
        "Bean Dad Meme Evolution",
        "The Most Interesting Man in the World Meme Culture",
        "Surprised Pikachu Meme Trends",
        "Feeling Cute Meme Culture",
        "Doge Meme Trends",
        "Epic Sax Guy Meme Evolution",
        "Swole Doge Meme Trends",
        "The Rock Driving Meme Culture",
        "Baby Yoda Meme Trends",
        "Confused Math Lady Meme Trends",
        "Distracted Boyfriend Meme Evolution",
        "Bean Dad Meme Culture",
        "Mocking SpongeBob Meme Trends",
        "Surprised Pikachu Meme Evolution",
        "Feeling Cute Meme Trends",
        "Doge Meme Culture",
        "Epic Sax Guy Meme Culture",
        "The Most Interesting Man in the World Meme Evolution",
        "Swole Doge Meme Trends",
        "Baby Yoda Meme Trends",
        "Confused Nick Young Meme Culture",
        "Distracted Boyfriend Meme Trends",
        "Mocking SpongeBob Meme Evolution",
        "Bean Dad Meme Culture",
        "Surprised Pikachu Meme Trends",
        "Feeling Cute Meme Evolution",
        "Doge Meme Culture",
        "Epic Sax Guy Meme Trends",
        "The Rock Driving Meme Culture",
        "Swole Doge Meme Evolution",
        "Baby Yoda Meme Trends",
        "Confused Math Lady Meme Culture",
        "Distracted Boyfriend Meme Evolution",
        "Mocking SpongeBob Meme Trends",
        "Bean Dad Meme Culture",
        "Surprised Pikachu Meme Trends",
        "Feeling Cute Meme Culture",
        "Doge Meme Evolution",
        "Epic Sax Guy Meme Trends",
        "The Rock Driving Meme Culture",
        "Swole Doge Meme Evolution",
        "Baby Yoda Meme Trends",
        "Confused Nick Young Meme Culture",
        "Distracted Boyfriend Meme Trends",
        "Mocking SpongeBob Meme Evolution",
        "Bean Dad Meme Culture",
        "Surprised Pikachu Meme Trends",
        "Feeling Cute Meme Evolution",
        "Doge Meme Trends",
        "Epic Sax Guy Meme Culture",
        "The Rock Driving Meme Trends",
        "Swole Doge Meme Evolution",
        "Baby Yoda Meme Culture",
        "Confused Math Lady Meme Trends",
        "Distracted Boyfriend Meme Evolution",
        "Mocking SpongeBob Meme Culture",
        "Bean Dad Meme Trends",
        "Surprised Pikachu Meme Culture",
        "Feeling Cute Meme Trends",
        "Doge Meme Evolution",
        "Epic Sax Guy Meme Culture",
        "The Rock Driving Meme Trends",
        "Swole Doge Meme Evolution",
        "Baby Yoda Meme Culture",
        "Confused Nick Young Meme Trends",
        "Distracted Boyfriend Meme Culture",
        "Mocking SpongeBob Meme Evolution",
        "Bean Dad Meme Trends",
        "Surprised Pikachu Meme Culture",
        "Feeling Cute Meme Evolution",
        "Doge Meme Culture",
        "Epic Sax Guy Meme Trends",
        "The Rock Driving Meme Culture",
        "Swole Doge Meme Evolution",
        "Baby Yoda Meme Trends",
        "Confused Math Lady Meme Culture",
        "Distracted Boyfriend Meme Evolution",
        "Mocking SpongeBob Meme Trends",
        "Bean Dad Meme Culture",
        "Surprised Pikachu Meme Trends",
        "Feeling Cute Meme Evolution",
        "Doge Meme Culture",
        "Epic Sax Guy Meme Trends",
       
    
];
const science = [
    "The theory of relativity",
    "Quantum mechanics",
    "The structure of DNA",
    "The role of mitochondria in cells",
    "The process of photosynthesis",
    "The laws of thermodynamics",
    "The principles of natural selection",
    "The big bang theory",
    "Plate tectonics and earthquakes",
    "The evolution of species",
    "Genetic engineering and CRISPR",
    "The human genome project",
    "The concept of dark matter",
    "The role of enzymes in biochemical reactions",
    "Neuroscience and brain function",
    "The study of black holes",
    "The principles of classical mechanics",
    "The behavior of gases under pressure",
    "The structure of the universe",
    "Climate change and global warming",
    "The study of extraterrestrial life",
    "The impact of pollution on ecosystems",
    "The principles of electromagnetism",
    "Astrobiology and the search for life on Mars",
    "The development of antibiotics",
    "The theory of evolution by natural selection",
    "The study of human anatomy",
    "The role of quantum entanglement",
    "The impact of renewable energy sources",
    "The principles of fluid dynamics",
    "The genetics of hereditary diseases",
    "The study of particle physics",
    "The concept of the multiverse",
    "The study of cellular processes",
    "The role of microorganisms in ecosystems",
    "The study of human evolution",
    "The development of vaccines",
    "The impact of artificial intelligence on science",
    "The study of chemical reactions",
    "The structure and function of proteins",
    "The role of stem cells in regenerative medicine",
    "The principles of chaos theory",
    "The impact of space exploration on science",
    "The study of marine biology",
    "The concept of dark energy",
    "The principles of genetic inheritance",
    "The role of antioxidants in health",
]







let generatedtopic = document.querySelector('.generated-topic');


function generateTopic(value){
    if(value === 'tech'){
       randomTopicForTech();
    }
    else if(value === 'history'){
       randomTopicForHistory();
    }
    else if(value === 'movie'){
        randomTopicForMovie();
    }else if(value === 'science'){
        randomTopicForScience();
    }
    else if(value === 'memes'){
        randomTopicForMemes();
    }

    

}



// Function to get a random topic
function randomTopicForTech() {
    let usedIndices = [];
    if (tech.length === 0) {
        document.querySelector('.generated-topic').innerHTML = 'No more topics available. Refresh the page to restart.';
        return;
    }
    
    // Get a random index
    const randomIndex = Math.floor(Math.random() * tech.length);
    // Select the topic
    const topic = tech[randomIndex];
    // Remove the topic from the array
    tech.splice(randomIndex, 1);
    // Display the topic
    document.querySelector('.generated-topic').innerHTML = topic;
}
function randomTopicForMovie() {
    let usedIndices = [];
    if (movie.length === 0) {
        document.querySelector('.generated-topic').innerHTML = 'No more topics available. Refresh the page to restart.';
        return;
    }
    
    // Get a random index
    const randomIndex = Math.floor(Math.random() * movie.length);
    // Select the topic
    const topic = movie[randomIndex];
    // Remove the topic from the array
    movie.splice(randomIndex, 1);
    // Display the topic
    document.querySelector('.generated-topic').innerHTML = topic;
}
function randomTopicForHistory() {
    let usedIndices = [];
    if (history.length === 0) {
        document.querySelector('.generated-topic').innerHTML = 'No more topics available. Refresh the page to restart.';
        return;
    }
    
    // Get a random index
    const randomIndex = Math.floor(Math.random() * history.length);
    // Select the topic
    const topic = history[randomIndex];
    // Remove the topic from the array
    history.splice(randomIndex, 1);
    // Display the topic
    document.querySelector('.generated-topic').innerHTML = topic;
}
function randomTopicForMemes() {
    let usedIndices = [];
    if (memes.length === 0) {
        document.querySelector('.generated-topic').innerHTML = 'No more topics available. Refresh the page to restart.';
        return;
    }
    
    // Get a random index
    const randomIndex = Math.floor(Math.random() * memes.length);
    // Select the topic
    const topic = memes[randomIndex];
    // Remove the topic from the array
    memes.splice(randomIndex, 1);
    // Display the topic
    document.querySelector('.generated-topic').innerHTML = topic;
}
function randomTopicForScience() {
    let usedIndices = [];
    if (memes.length === 0) {
        document.querySelector('.generated-topic').innerHTML = 'No more topics available. Refresh the page to restart.';
        return;
    }
    
    // Get a random index
    const randomIndex = Math.floor(Math.random() * science.length);
    // Select the topic
    const topic = science[randomIndex];
    // Remove the topic from the array
    science.splice(randomIndex, 1);
    // Display the topic
    document.querySelector('.generated-topic').innerHTML = topic;
}

function refreshingPage(){
    window.location.reload();
}